### ISSUE TITLE
using `MQFM` to apply a Surplus production models in CHile

### ISSUE THREAD

**Issue by MauroMardones** [haddonm/MQMF#1]
I notice that the `MGFM` package is not updated, would this be a problem to apply the library and functions to a current Chilean fishery case?
Best and thanks

**Comment by haddonm** [comment]
Hi there,

I have not updated MQMF for a while because there have been no changes of
any great import. The very latest version is on GitHub, but it differs from
the CRAN version only in terms of some very minor text changes in the help
files not in the functions. So, if you used it earlier it should still be
working now.

Best regards
Malcolm

Dr Malcolm Haddon
Adjunct Professor, IMAS, University of Tasmania
Honorary Research Fellow CSIRO Oceans and Atmosphere
mob: +61 (0) 409 941 891
alt email: ***@***.***
GitHub: https://github.com/haddonm
GitBook: https://haddonm.github.io/URMQMF
CRAN: https://CRAN.R-project.org/package=MQMF
<https://cran.r-project.org/package=MQMF>

**Comment by MauroMardones** [comment]
That sounds promising. I feel better now, as I will use an example from the book.

Thank you very much, Malcolm.
